version: '3'

services:
  ghost:
    image: ghost:2.21.0
    restart: always
    ports:
      - 2368:2368
    environment:
      NODE_ENV: development
      url: "http://self-made-south:2368"
      database__client: "mysql"
      database__connection__host: "db"
      database__connection__port: 3306
      database__connection__user: "ghost"
      database__connection__password: "password"
      database__connection__database: "ghost"
    volumes:
      - ../../../ghost/theme:/var/lib/ghost/content/themes/self-made-south
      - ./entrypoint.sh:/var/lib/ghost/entrypoint.sh
    depends_on:
      - db

  db:
    image: mysql:5.7.26
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "ghost"
      MYSQL_USER: "ghost"
      MYSQL_PASSWORD: "password"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql:
