version: '3'

services:
  ghost:
    image: ghost:2.21.0
    restart: always
    ports:
    - 2368:2368
    environment:
      NODE_ENV: development
      url: "http://self-made-south:2368"
      database__client: "mysql"
      database__connection__host: "db"
      database__connection__port: 3306
      database__connection__user: "ghost"
      database__connection__password: "password"
      database__connection__database: "ghost"
    depends_on:
    - db
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:2368 || exit 1"]
      timeout: 5s
      retries: 10

  gatsby:
    build:
      context: .
      dockerfile: containers/gatsby/Dockerfile
    working_dir: /opt/self-made-south
    entrypoint: /bin/bash -c 'tail -f /dev/null'
    ports:
    - 8000:8000
    environment:
      YARN_CACHE_FOLDER: /opt/yarn-cache
    volumes:
    - ../../../:/opt/self-made-south
    - yarn-cache:/opt/yarn-cache
    depends_on:
    - ghost
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8000 || exit 1"]
      timeout: 5s
      retries: 10

  db:
    image: mysql:5.7.26
    restart: always
    volumes:
    - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "ghost"
      MYSQL_USER: "ghost"
      MYSQL_PASSWORD: "password"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

volumes:
  mysql:
  yarn-cache:
